// While not used in the front-end, this list of categories
// can be used to create a select input, using the description
// property and a regex to organize it into groups of sub-categories.
// List taken from simple.com
export const Categories = new GqlEnum({
  name: `Categories`,
  description: `A list of Categories for Payment transactions.`,
  values: {
    // Income
    Bonus: { description: `Income: Bonus` },
    Commission: { description: `Income: Commission` },
    Interest: { description: `Income: Interest` },
    OtherIncome: { description: `Income: Other Income` },
    Paycheck: { description: `Income: Paycheck` },
    Reimbursement: { description: `Income: Reimbursement` },
    RentalIncome: { description: `Income: RentalIncome` },
    // Business
    BusinessClothing: { description: `Business: Business Clothing` },
    BusinessServices: { description: `Business: Business Services` },
    BusinessSupplies: { description: `Business: Business Supplies` },
    Meals: { description: `Business: Meals` },
    Travel: { description: `Business: Travel` },
    // Children
    Activities: { description: `Children: Activities` },
    Allowance: { description: `Children: Allowance` },
    BabySupplies: { description: `Children: Baby Supplies` },
    Childcare: { description: `Children: Childcare` },
    KidsClothing: { description: `Children: Kids Clothing` },
    KidsEducation: { description: `Children: Kids Education` },
    Toys: { description: `Children: Toys` },
    // Culture
    Art: { description: `Culture: Art` },
    Books: { description: `Culture: Books` },
    Dance: { description: `Culture: Dance` },
    Games: { description: `Culture: Games` },
    Movies: { description: `Culture: Movies` },
    Music: { description: `Culture: Music` },
    News: { description: `Culture: News` },
    RandomFun: { description: `Culture: Random Fun` },
    TV: { description: `Culture: TV` },
    // Education
    BooksSupplies: { description: `Education: Books & Supplies` },
    RoomBoard: { description: `Education: Room & Board` },
    StudentLoans: { description: `Education: Student Loans` },
    TuitionFees: { description: `Education: Tuition & Fees` },
    // Fees
    ATMFees: { description: `Fees: ATM Fees` },
    InvestmentFees: { description: `Fees: Investment Fees` },
    OtherFees: { description: `Fees: Other Fees` },
    // Financial
    Accounting: { description: `Financial: Accounting` },
    FinancialAdvice: { description: `Financial: Financial Advice` },
    LifeInsurance: { description: `Financial: Life Insurance` },
    MoneyTransfers: { description: `Financial: Money Transfers` },
    OtherFinancial: { description: `Financial: Other Financial` },
    TaxPreparation: { description: `Financial: Tax Preparation` },
    TaxesFederal: { description: `Financial: Taxes, Federal` },
    TaxesOther: { description: `Financial: Taxes, Other` },
    TaxesState: { description: `Financial: Taxes, State` },
    CreditCardPayment: { description: `Financial: Credit Card Payment` },
    // Sports & Fitness
    Camping: { description: `Sports & Fitness: Camping` },
    FitnessGear: { description: `Sports & Fitness: Fitness Gear` },
    Golf: { description: `Sports & Fitness: Golf` },
    Memberships: { description: `Sports & Fitness: Memberships` },
    OtherSportsFitness: { description: `Sports & Fitness: Other Sports & Fitness` },
    SportingEvents: { description: `Sports & Fitness: Sporting Events` },
    SportingGoods: { description: `Sports & Fitness: Sporting Goods` },
    // Food & Drink
    AlcoholBars: { description: `Food & Drink: Alcohol & Bars` },
    FastFood: { description: `Food & Drink: Fast Food` },
    Groceries: { description: `Food & Drink: Groceries` },
    OtherFoodDrink: { description: `Food & Drink: Other Food & Drink` },
    Restaurants: { description: `Food & Drink: Restaurants` },
    Snacks: { description: `Food & Drink: Snacks` },
    Tobacco: { description: `Food & Drink: Tobacco` },
    // Gifts & Donations
    Charities: { description: `Gifts & Donations: Charities` },
    Gifts: { description: `Gifts & Donations: Gifts` },
    // Health & Medical
    CareFacilities: { description: `Health & Medical: Care Facilities` },
    Dentist: { description: `Health & Medical: Dentist` },
    Doctor: { description: `Health & Medical: Doctor` },
    MedicalEquipment: { description: `Health & Medical: Medical Equipment` },
    Eyes: { description: `Health & Medical: Eyes` },
    HealthInsurance: { description: `Health & Medical: Health Insurance` },
    OtherHealthMedical: { description: `Health & Medical: Other Health & Medical` },
    Pharmacies: { description: `Health & Medical: Pharmacies` },
    Prescriptions: { description: `Health & Medical: Prescriptions` },
    // Home
    Furnishings: { description: `Home: Furnishings` },
    HomeInsurance: { description: `Home: Home Insurance` },
    HomePurchase: { description: `Home: Home Purchase` },
    HomeServices: { description: `Home: Home Services` },
    HomeSupplies: { description: `Home: Home Supplies` },
    RepairsImprovement: { description: `Home: Repairs & Improvement` },
    LawnGarden: { description: `Home: Lawn & Garden` },
    Mortgage: { description: `Home: Mortgage` },
    Moving: { description: `Home: Moving` },
    OtherHome: { description: `Home: Other Home` },
    PropertyTax: { description: `Home: Property Tax` },
    Rent: { description: `Home: Rent` },
    RentersInsurance: { description: `Home: Renter's Insurance` },
    Storage: { description: `Home: Storage` },
    // Investment
    EducationInvestment: { description: `Investment: Education Investment` },
    OtherInvestments: { description: `Investment: Other Investments` },
    Retirement: { description: `Investment: Retirement` },
    StocksMutualFunds: { description: `Investment: Stocks & Mutual Funds` },
    // Legal
    LegalFees: { description: `Legal: Legal Fees` },
    LegalServices: { description: `Legal: Legal Services` },
    OtherLegalCosts: { description: `Legal: Other Legal Costs` },
    // Office
    OfficeEquipment: { description: `Office: Office Equipment` },
    PostageShipping: { description: `Office: Postage & Shipping` },
    OfficeSupplies: { description: `Office: Office Supplies` },
    OtherOffice: { description: `Office: Other Office` },
    // Personal
    Accessories: { description: `Personal: Accessories` },
    Beauty: { description: `Personal: Beauty` },
    BodyEnhancement: { description: `Personal: Body Enhancement` },
    Clothing: { description: `Personal: Clothing` },
    Counseling: { description: `Personal: Counseling` },
    Hair: { description: `Personal: Hair` },
    Hobbies: { description: `Personal: Hobbies` },
    Jewelry: { description: `Personal: Jewelry` },
    Laundry: { description: `Personal: Laundry` },
    OtherPersonal: { description: `Personal: Other Personal` },
    Religion: { description: `Personal: Religion` },
    Shoes: { description: `Personal: Shoes` },
    SpaMassage: { description: `Personal: Spa & Massage` },
    // Pets
    PetFood: { description: `Pets: Pet Food` },
    PetGrooming: { description: `Pets: Pet Grooming` },
    PetMedicine: { description: `Pets: Pet Medicine` },
    PetSupplies: { description: `Pets: Pet Supplies` },
    Veterinarian: { description: `Pets: Veterinarian` },
    // Technology
    DomainsHosting: { description: `Technology: Domains & Hosting` },
    Hardware: { description: `Technology: Hardware` },
    OnlineServices: { description: `Technology: Online Services` },
    Software: { description: `Technology: Software` },
    // Transportation
    AutoInsurance: { description: `Transportation: Auto Insurance` },
    AutoPayment: { description: `Transportation: Auto Payment` },
    AutoServices: { description: `Transportation: Auto Services` },
    AutoSupplies: { description: `Transportation: Auto Supplies` },
    Bicycle: { description: `Transportation: Bicycle` },
    BoatsMarine: { description: `Transportation: Boats & Marine` },
    Gas: { description: `Transportation: Gas` },
    OtherTransportation: { description: `Transportation: Other Transportation` },
    ParkingTickets: { description: `Transportation: Parking Tickets` },
    ParkingTolls: { description: `Transportation: Parking & Tolls` },
    PublicTransit: { description: `Transportation: Public Transit` },
    Shipping: { description: `Transportation: Shipping` },
    Taxis: { description: `Transportation: Taxis` },
    // Travel
    CarRental: { description: `Travel: Car Rental` },
    Flights: { description: `Travel: Flights` },
    Hotels: { description: `Travel: Hotels` },
    ToursCruises: { description: `Travel: Tours & Cruises` },
    Train: { description: `Travel: Train` },
    TravelBuses: { description: `Travel: Travel Buses` },
    TravelDining: { description: `Travel: Travel Dining` },
    TravelEntertainment: { description: `Travel: Travel Entertainment` },
    // Uncategorized
    Cash: { description: `Uncategorized: Cash` },
    OtherShopping: { description: `Uncategorized: Other Shopping` },
    Unknown: { description: `Uncategorized: Unknown` },
    // Utilities
    Cable: { description: `Utilities: Cable` },
    Electricity: { description: `Utilities: Electricity` },
    GasFuel: { description: `Utilities: Gas & Fuel` },
    Internet: { description: `Utilities: Internet` },
    OtherUtilities: { description: `Utilities: Other Utilities` },
    Phone: { description: `Utilities: Phone` },
    Trash: { description: `Utilities: Trash` },
    WaterSewer: { description: `Utilities: Water & Sewer` }
  }
})
